name: RSS to Bluesky Poster

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  post-to-bluesky:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser atproto
          
      - name: Create feed tracker if not exists
        run: |
          if [ ! -f "posted_entries.json" ]; then
            echo "[]" > posted_entries.json
          fi
          
      - name: Process RSS and post to Bluesky
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
          MAX_POSTS: ${{ secrets.MAX_POSTS }}
        run: |
          cat << 'EOF' > process_feed.py
          import feedparser
          import os
          import json
          import time
          from atproto import Client
          
          def get_posted_entries():
              try:
                  with open('posted_entries.json', 'r') as f:
                      return set(json.load(f))
              except:
                  return set()
          
          def save_posted_entries(posted_entries):
              with open('posted_entries.json', 'w') as f:
                  json.dump(list(posted_entries), f)
          
          def post_to_bluesky(client, entry):
              try:
                  # Get the title and URL
                  title = entry.title.strip()
                  url = entry.link
                  
                  # Add an invisible character after the title to separate it from the URL
                  post_text = f"{title}\u200B"
                  
                  # Create facet for the hidden link at the end
                  byte_start = len(post_text.encode('utf-8'))
                  byte_end = byte_start + len(url.encode('utf-8'))
                  
                  # Create the post with embedded URL
                  resp = client.send_post(
                      text=f"{post_text}{url}",
                      facets=[{
                          "index": {
                              "byteStart": byte_start,
                              "byteEnd": byte_end
                          },
                          "features": [{
                              "$type": "app.bsky.richtext.facet#link",
                              "uri": url
                          }]
                      }]
                  )
                  
                  # Add delay between posts to avoid rate limiting
                  time.sleep(2)
                  return True
              except Exception as e:
                  print(f"Error posting to Bluesky: {e}")
                  return False
          
          def main():
              # Initialize Bluesky client
              client = Client()
              client.login(os.environ['BLUESKY_HANDLE'], os.environ['BLUESKY_PASSWORD'])
              
              # Get max posts to process (default to 10 if not set)
              max_posts = int(os.environ.get('MAX_POSTS', 10))
              
              # Parse RSS feed
              feed = feedparser.parse(os.environ['RSS_FEED_URL'])
              posted_entries = get_posted_entries()
              
              # Sort entries by date (newest first)
              entries = sorted(
                  feed.entries,
                  key=lambda entry: entry.get('published_parsed', entry.get('updated_parsed')),
                  reverse=True
              )
              
              # Take only the most recent entries based on MAX_POSTS
              entries = entries[:max_posts]
              
              # Reverse the order to post oldest first
              entries.reverse()
              
              # Track newly posted entries
              newly_posted = set()
              
              # Process entries
              for entry in entries:
                  entry_id = entry.id
                  
                  # Only post if we haven't posted this before
                  if entry_id not in posted_entries:
                      if post_to_bluesky(client, entry):
                          newly_posted.add(entry_id)
                          print(f"Successfully posted: {entry.title}")
              
              # Update our tracking with successfully posted entries
              posted_entries.update(newly_posted)
              save_posted_entries(posted_entries)
              
              # Print summary
              print(f"Processed the last {max_posts} posts from RSS feed")
              print(f"Posted {len(newly_posted)} new entries to Bluesky")
          
          if __name__ == "__main__":
              main()
          EOF
          
          python process_feed.py
          
      - name: Commit changes to tracker
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add posted_entries.json
          git commit -m "Update posted entries tracking" || exit 0
          git push
